name: Render Deploy

on:
  push:
    branches:
      - main # mainブランチにプッシュされた時のみ実行
  pull_request:
    branches:
      - main # mainブランチへのプルリクエスト時に実行

jobs:
  deploy:
    name: Deploy to Render
    runs-on: ubuntu-latest
    steps:
      - uses: ttskch/render-deploy@v1.0.0
        with:
          api-key: ${{ secrets.RENDER_API_KEY }}
          service-id: ${{ secrets.RENDER_SERVICE_ID }}
          interval: 20 # デプロイステータスのチェック間隔（秒）
          timeout: 300 # タイムアウトまでの時間（秒）
